"use client"
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Wrapper from './wrapper'
import { Provider } from './provider'
import Navbar from '@/components/navbar'
import { usePathname } from 'next/navigation'

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const path = usePathname()
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <main className={`flex min-h-screen flex-col items-center ${path === '/' ? 'bg-hero-background-image bg-no-repeat bg-cover' : 'bg-white'}  `}>
            <Navbar />
            {children}
          </main>
        </Provider>
      </body>
    </html>
  );
}

